### ISSUE TITLE
This is not LISAM.

### ISSUE THREAD

**Issue by mohag519** [TheZoq2/slightly-less-shitty-lisam#2]
Screenshots for the first "before" and "after" is showing SharePoint Online functionality being hidden with this "awesome" css, it is not specific for LISAM. I feel like this has to be pointed out in the readme so people don't falsely believe that they are only hiding something locally for LISAM but actually making the header dissapear for the entire sharepoint online. This could cause problem for people who don't realize what the are installing and later get problems down the road visiting other sharepoint online sites.

**Comment by TheZoq2** [comment]
If I understand the issue correctly, this problem is mitigated by the `@-moz-document url-prefix("https://liuonline.sharepoint.com/")` line which only activates the CSS on lisam. Or are there other LIU sharepoint sites on that same domain?

**Comment by TheZoq2** [comment]
With that said, adding a disclaimer in the readme that problems might occur, both on lisam and on related sites and that disabling the usercss might solve that is a good idea

**Comment by mohag519** [comment]
In the future more applications of LiU might get lifted to liuonline.sharepoint.com. Also since Microsoft are in control of these areas of the page we never know if they in the future add functionality in these parts that actually ARE important to users. We might inject functionality there ourselves aswell in the future (for example a "megamenu"). Right now the "In english/swedish" is injected by, us (LiU IT). As long as people know what they are doing it's fine but a lot of users will not understand what they are hiding.

**Comment by TheZoq2** [comment]
> us (LiU IT)

I'm kind of surprised that this repo has spread this far, I hope it doesn't cause too many issues for you :) 

> We might inject functionality there ourselves aswell in the future (for example a "megamenu"). Right now the "In english/swedish" is injected by, us (LiU IT)

That does sound like a problem, if you do add future functionality, feel free to let me know and i'll make the neccesary changes.

I also added a short disclaimer which I think I will expand later today, let me know if I should add anything else.

I might also change the url filter for most rules to only apply to the student protal in order to further mitigate potential problems.

**Comment by mohag519** [comment]
Great! Oops.  I'm here as a private person, not through IT 😓
